name: 'Trigger index build'
description: 'triggers a rebuild of the index'
runs:
  using: "composite"
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: chmod +x "${{ github.action_path }}/dispatch.sh"
      shell: bash
    - run: dispatch.sh  "${{ github.token }}"
      shell: bash
       
      
